services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=inventory
    networks:
      - e-commerce-network
    volumes:
      - pgsql:/var/lib/postgresql/data
  service:
        build:
          context: .
          dockerfile: Dockerfile.dev
        ports:
          - 8001:80
        environment:
          SERVER_PORT: 80
        networks:
          - e-commerce-network
        volumes:
          - ./src:/app/src
          - .env:/app/.env
          - ./pom.xml:/app/pom.xml
          - ./target:/app/target
networks:
    e-commerce-network:
        external: true
volumes:
    pgsql:
        driver: local
